### ISSUE TITLE
Can this be improved further? 

### ISSUE THREAD

**Issue by silicahd** [angel-dart/paginate#5]
*This issue was automatically moved to: https://github.com/angel-dart/angel/issues/192.

**Comment by thosakwe** [comment]
Sorry for the late response, but there is the `goToPage` function in `Paginate`. That being said, since the paginator isn't tied to the ORM, you would have to fetch+deserialize all results before doing that.

However, the base `Query` class in `package:angel_orm` has `offset` and `limit`, which can be easily used for pagination.
